<div class="loadingio-spinner-dual-ring-j4wquecdqh8"><div class="ldio-bfrdtirvkl">
<div></div><div><div></div></div>
</div></div>
<style type="text/css">
@keyframes ldio-bfrdtirvkl {
  0% { transform: rotate(0) }
  100% { transform: rotate(360deg) }
}
.ldio-bfrdtirvkl div { box-sizing: border-box!important }
.ldio-bfrdtirvkl > div {
  position: absolute;
  width: 22px;
  /* width :52px;
  height: 52px; */
  height: 22px;
  top: 74px;
  left: 74px;
  border-radius: 50%;
  border: 2px solid #000;
  border-color: #fe718d transparent #fe718d transparent;
  animation: ldio-bfrdtirvkl 0.7874015748031495s linear infinite;
}
.ldio-bfrdtirvkl > div:nth-child(2) { border-color: transparent }
.ldio-bfrdtirvkl > div:nth-child(2) div {
  position: absolute;
  width: 100%;
  height: 100%;
  transform: rotate(45deg);
}
.ldio-bfrdtirvkl > div:nth-child(2) div:before, .ldio-bfrdtirvkl > div:nth-child(2) div:after { 
  content: "";
  display: block;
  position: absolute;
  /* width: 4px;
  height: 4px; */
  top: -4px;
  left: 20px;
  background: #fe718d;
  border-radius: 50%;
  box-shadow: 0 48px 0 0 #fe718d;
}
.ldio-bfrdtirvkl > div:nth-child(2) div:after { 
  left: -4px;
  top: 20px;
  box-shadow: 48px 0 0 0 #fe718d;
}
.loadingio-spinner-dual-ring-j4wquecdqh8 {
  /* width: 200px;
  height: 200px; */
  width:100px;
  height:100px;
  display: inline-block;
  overflow: hidden;
  background: none;
}
.ldio-bfrdtirvkl {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-bfrdtirvkl div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>